// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkLookup.Models;

namespace ParkLookup.Migrations
{
    [DbContext(typeof(ParkLookupContext))]
    partial class ParkLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkLookup.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("NationalParkCamping");

                    b.Property<bool>("NationalParkFishing");

                    b.Property<string>("NationalParkHighlight");

                    b.Property<bool>("NationalParkHiking");

                    b.Property<string>("NationalParkName");

                    b.Property<string>("NationalParkState");

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");
                });

            modelBuilder.Entity("ParkLookup.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("StateParkCamping");

                    b.Property<bool>("StateParkFishing");

                    b.Property<string>("StateParkHighlight");

                    b.Property<bool>("StateParkHiking");

                    b.Property<string>("StateParkName");

                    b.Property<string>("StateParkState");

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");
                });
#pragma warning restore 612, 618
        }
    }
}
